.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */


glabel sqrtf
    /* C4EA0 800C42A0 03E00008 */  jr         $ra
    /* C4EA4 800C42A4 46006004 */   sqrt.s    $fv0, $fa0
endlabel sqrtf
    /* C4EA8 800C42A8 00000000 */  nop
    /* C4EAC 800C42AC 00000000 */  nop
