.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel bcopy
    /* CD880 800CCC80 10C0001A */  beqz       $a2, .L800CCCEC
    /* CD884 800CCC84 00A03825 */   or        $a3, $a1, $zero
    /* CD888 800CCC88 10850018 */  beq        $a0, $a1, .L800CCCEC
    /* CD88C 800CCC8C 00A4082A */   slt       $at, $a1, $a0
    /* CD890 800CCC90 54200008 */  bnel       $at, $zero, .L800CCCB4
    /* CD894 800CCC94 28C10010 */   slti      $at, $a2, 0x10
    /* CD898 800CCC98 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
    /* CD89C 800CCC9C 00A2082A */  slt        $at, $a1, $v0
    /* CD8A0 800CCCA0 50200004 */  beql       $at, $zero, .L800CCCB4
    /* CD8A4 800CCCA4 28C10010 */   slti      $at, $a2, 0x10
    /* CD8A8 800CCCA8 1000005B */  b          .L800CCE18
    /* CD8AC 800CCCAC 28C10010 */   slti      $at, $a2, 0x10
    /* CD8B0 800CCCB0 28C10010 */  slti       $at, $a2, 0x10
  .L800CCCB4:
    /* CD8B4 800CCCB4 14200005 */  bnez       $at, .L800CCCCC
    /* CD8B8 800CCCB8 00000000 */   nop
    /* CD8BC 800CCCBC 30820003 */  andi       $v0, $a0, 0x3
    /* CD8C0 800CCCC0 30A30003 */  andi       $v1, $a1, 0x3
    /* CD8C4 800CCCC4 1043000B */  beq        $v0, $v1, .L800CCCF4
    /* CD8C8 800CCCC8 00000000 */   nop
  .L800CCCCC:
    /* CD8CC 800CCCCC 10C00007 */  beqz       $a2, .L800CCCEC
    /* CD8D0 800CCCD0 00000000 */   nop
    /* CD8D4 800CCCD4 00861821 */  addu       $v1, $a0, $a2
  .L800CCCD8:
    /* CD8D8 800CCCD8 80820000 */  lb         $v0, 0x0($a0)
    /* CD8DC 800CCCDC 24840001 */  addiu      $a0, $a0, 0x1
    /* CD8E0 800CCCE0 24A50001 */  addiu      $a1, $a1, 0x1
    /* CD8E4 800CCCE4 1483FFFC */  bne        $a0, $v1, .L800CCCD8
    /* CD8E8 800CCCE8 A0A2FFFF */   sb        $v0, -0x1($a1)
  .L800CCCEC:
    /* CD8EC 800CCCEC 03E00008 */  jr         $ra
    /* CD8F0 800CCCF0 00E01025 */   or        $v0, $a3, $zero
  .L800CCCF4:
    /* CD8F4 800CCCF4 10400018 */  beqz       $v0, .L800CCD58
    /* CD8F8 800CCCF8 24010001 */   addiu     $at, $zero, 0x1
    /* CD8FC 800CCCFC 1041000F */  beq        $v0, $at, .L800CCD3C
    /* CD900 800CCD00 24010002 */   addiu     $at, $zero, 0x2
    /* CD904 800CCD04 50410008 */  beql       $v0, $at, .L800CCD28
    /* CD908 800CCD08 84820000 */   lh        $v0, 0x0($a0)
    /* CD90C 800CCD0C 80820000 */  lb         $v0, 0x0($a0)
    /* CD910 800CCD10 24840001 */  addiu      $a0, $a0, 0x1
    /* CD914 800CCD14 24A50001 */  addiu      $a1, $a1, 0x1
    /* CD918 800CCD18 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* CD91C 800CCD1C 1000000E */  b          .L800CCD58
    /* CD920 800CCD20 A0A2FFFF */   sb        $v0, -0x1($a1)
    /* CD924 800CCD24 84820000 */  lh         $v0, 0x0($a0)
  .L800CCD28:
    /* CD928 800CCD28 24840002 */  addiu      $a0, $a0, 0x2
    /* CD92C 800CCD2C 24A50002 */  addiu      $a1, $a1, 0x2
    /* CD930 800CCD30 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* CD934 800CCD34 10000008 */  b          .L800CCD58
    /* CD938 800CCD38 A4A2FFFE */   sh        $v0, -0x2($a1)
  .L800CCD3C:
    /* CD93C 800CCD3C 80820000 */  lb         $v0, 0x0($a0)
    /* CD940 800CCD40 84830001 */  lh         $v1, 0x1($a0)
    /* CD944 800CCD44 24840003 */  addiu      $a0, $a0, 0x3
    /* CD948 800CCD48 24A50003 */  addiu      $a1, $a1, 0x3
    /* CD94C 800CCD4C 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* CD950 800CCD50 A0A2FFFD */  sb         $v0, -0x3($a1)
    /* CD954 800CCD54 A4A3FFFE */  sh         $v1, -0x2($a1)
  .L800CCD58:
    /* CD958 800CCD58 28C10020 */  slti       $at, $a2, 0x20
    /* CD95C 800CCD5C 54200016 */  bnel       $at, $zero, .L800CCDB8
    /* CD960 800CCD60 28C10010 */   slti      $at, $a2, 0x10
    /* CD964 800CCD64 8C820000 */  lw         $v0, 0x0($a0)
    /* CD968 800CCD68 8C830004 */  lw         $v1, 0x4($a0)
    /* CD96C 800CCD6C 8C880008 */  lw         $t0, 0x8($a0)
    /* CD970 800CCD70 8C89000C */  lw         $t1, 0xC($a0)
    /* CD974 800CCD74 8C8A0010 */  lw         $t2, 0x10($a0)
    /* CD978 800CCD78 8C8B0014 */  lw         $t3, 0x14($a0)
    /* CD97C 800CCD7C 8C8C0018 */  lw         $t4, 0x18($a0)
    /* CD980 800CCD80 8C8D001C */  lw         $t5, 0x1C($a0)
    /* CD984 800CCD84 24840020 */  addiu      $a0, $a0, 0x20
    /* CD988 800CCD88 24A50020 */  addiu      $a1, $a1, 0x20
    /* CD98C 800CCD8C 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* CD990 800CCD90 ACA2FFE0 */  sw         $v0, -0x20($a1)
    /* CD994 800CCD94 ACA3FFE4 */  sw         $v1, -0x1C($a1)
    /* CD998 800CCD98 ACA8FFE8 */  sw         $t0, -0x18($a1)
    /* CD99C 800CCD9C ACA9FFEC */  sw         $t1, -0x14($a1)
    /* CD9A0 800CCDA0 ACAAFFF0 */  sw         $t2, -0x10($a1)
    /* CD9A4 800CCDA4 ACABFFF4 */  sw         $t3, -0xC($a1)
    /* CD9A8 800CCDA8 ACACFFF8 */  sw         $t4, -0x8($a1)
    /* CD9AC 800CCDAC 1000FFEA */  b          .L800CCD58
    /* CD9B0 800CCDB0 ACADFFFC */   sw        $t5, -0x4($a1)
  .L800CCDB4:
    /* CD9B4 800CCDB4 28C10010 */  slti       $at, $a2, 0x10
  .L800CCDB8:
    /* CD9B8 800CCDB8 5420000E */  bnel       $at, $zero, .L800CCDF4
    /* CD9BC 800CCDBC 28C10004 */   slti      $at, $a2, 0x4
    /* CD9C0 800CCDC0 8C820000 */  lw         $v0, 0x0($a0)
    /* CD9C4 800CCDC4 8C830004 */  lw         $v1, 0x4($a0)
    /* CD9C8 800CCDC8 8C880008 */  lw         $t0, 0x8($a0)
    /* CD9CC 800CCDCC 8C89000C */  lw         $t1, 0xC($a0)
    /* CD9D0 800CCDD0 24840010 */  addiu      $a0, $a0, 0x10
    /* CD9D4 800CCDD4 24A50010 */  addiu      $a1, $a1, 0x10
    /* CD9D8 800CCDD8 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* CD9DC 800CCDDC ACA2FFF0 */  sw         $v0, -0x10($a1)
    /* CD9E0 800CCDE0 ACA3FFF4 */  sw         $v1, -0xC($a1)
    /* CD9E4 800CCDE4 ACA8FFF8 */  sw         $t0, -0x8($a1)
    /* CD9E8 800CCDE8 1000FFF2 */  b          .L800CCDB4
    /* CD9EC 800CCDEC ACA9FFFC */   sw        $t1, -0x4($a1)
  .L800CCDF0:
    /* CD9F0 800CCDF0 28C10004 */  slti       $at, $a2, 0x4
  .L800CCDF4:
    /* CD9F4 800CCDF4 1420FFB5 */  bnez       $at, .L800CCCCC
    /* CD9F8 800CCDF8 00000000 */   nop
    /* CD9FC 800CCDFC 8C820000 */  lw         $v0, 0x0($a0)
    /* CDA00 800CCE00 24840004 */  addiu      $a0, $a0, 0x4
    /* CDA04 800CCE04 24A50004 */  addiu      $a1, $a1, 0x4
    /* CDA08 800CCE08 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* CDA0C 800CCE0C 1000FFF8 */  b          .L800CCDF0
    /* CDA10 800CCE10 ACA2FFFC */   sw        $v0, -0x4($a1)
    /* CDA14 800CCE14 28C10010 */  slti       $at, $a2, 0x10
  .L800CCE18:
    /* CDA18 800CCE18 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* CDA1C 800CCE1C 14200005 */  bnez       $at, .L800CCE34
    /* CDA20 800CCE20 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
    /* CDA24 800CCE24 30820003 */  andi       $v0, $a0, 0x3
    /* CDA28 800CCE28 30A30003 */  andi       $v1, $a1, 0x3
    /* CDA2C 800CCE2C 1043000D */  beq        $v0, $v1, .L800CCE64
    /* CDA30 800CCE30 00000000 */   nop
  .L800CCE34:
    /* CDA34 800CCE34 10C0FFAD */  beqz       $a2, .L800CCCEC
    /* CDA38 800CCE38 00000000 */   nop
    /* CDA3C 800CCE3C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* CDA40 800CCE40 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* CDA44 800CCE44 00861823 */  subu       $v1, $a0, $a2
  .L800CCE48:
    /* CDA48 800CCE48 80820000 */  lb         $v0, 0x0($a0)
    /* CDA4C 800CCE4C 2484FFFF */  addiu      $a0, $a0, -0x1
    /* CDA50 800CCE50 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* CDA54 800CCE54 1483FFFC */  bne        $a0, $v1, .L800CCE48
    /* CDA58 800CCE58 A0A20001 */   sb        $v0, 0x1($a1)
    /* CDA5C 800CCE5C 03E00008 */  jr         $ra
    /* CDA60 800CCE60 00E01025 */   or        $v0, $a3, $zero
  .L800CCE64:
    /* CDA64 800CCE64 10400018 */  beqz       $v0, .L800CCEC8
    /* CDA68 800CCE68 24010003 */   addiu     $at, $zero, 0x3
    /* CDA6C 800CCE6C 1041000F */  beq        $v0, $at, .L800CCEAC
    /* CDA70 800CCE70 24010002 */   addiu     $at, $zero, 0x2
    /* CDA74 800CCE74 50410008 */  beql       $v0, $at, .L800CCE98
    /* CDA78 800CCE78 8482FFFE */   lh        $v0, -0x2($a0)
    /* CDA7C 800CCE7C 8082FFFF */  lb         $v0, -0x1($a0)
    /* CDA80 800CCE80 2484FFFF */  addiu      $a0, $a0, -0x1
    /* CDA84 800CCE84 24A5FFFF */  addiu      $a1, $a1, -0x1
    /* CDA88 800CCE88 24C6FFFF */  addiu      $a2, $a2, -0x1
    /* CDA8C 800CCE8C 1000000E */  b          .L800CCEC8
    /* CDA90 800CCE90 A0A20000 */   sb        $v0, 0x0($a1)
    /* CDA94 800CCE94 8482FFFE */  lh         $v0, -0x2($a0)
  .L800CCE98:
    /* CDA98 800CCE98 2484FFFE */  addiu      $a0, $a0, -0x2
    /* CDA9C 800CCE9C 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* CDAA0 800CCEA0 24C6FFFE */  addiu      $a2, $a2, -0x2
    /* CDAA4 800CCEA4 10000008 */  b          .L800CCEC8
    /* CDAA8 800CCEA8 A4A20000 */   sh        $v0, 0x0($a1)
  .L800CCEAC:
    /* CDAAC 800CCEAC 8082FFFF */  lb         $v0, -0x1($a0)
    /* CDAB0 800CCEB0 8483FFFD */  lh         $v1, -0x3($a0)
    /* CDAB4 800CCEB4 2484FFFD */  addiu      $a0, $a0, -0x3
    /* CDAB8 800CCEB8 24A5FFFD */  addiu      $a1, $a1, -0x3
    /* CDABC 800CCEBC 24C6FFFD */  addiu      $a2, $a2, -0x3
    /* CDAC0 800CCEC0 A0A20002 */  sb         $v0, 0x2($a1)
    /* CDAC4 800CCEC4 A4A30000 */  sh         $v1, 0x0($a1)
  .L800CCEC8:
    /* CDAC8 800CCEC8 28C10020 */  slti       $at, $a2, 0x20
    /* CDACC 800CCECC 54200016 */  bnel       $at, $zero, .L800CCF28
    /* CDAD0 800CCED0 28C10010 */   slti      $at, $a2, 0x10
    /* CDAD4 800CCED4 8C82FFFC */  lw         $v0, -0x4($a0)
    /* CDAD8 800CCED8 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* CDADC 800CCEDC 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* CDAE0 800CCEE0 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* CDAE4 800CCEE4 8C8AFFEC */  lw         $t2, -0x14($a0)
    /* CDAE8 800CCEE8 8C8BFFE8 */  lw         $t3, -0x18($a0)
    /* CDAEC 800CCEEC 8C8CFFE4 */  lw         $t4, -0x1C($a0)
    /* CDAF0 800CCEF0 8C8DFFE0 */  lw         $t5, -0x20($a0)
    /* CDAF4 800CCEF4 2484FFE0 */  addiu      $a0, $a0, -0x20
    /* CDAF8 800CCEF8 24A5FFE0 */  addiu      $a1, $a1, -0x20
    /* CDAFC 800CCEFC 24C6FFE0 */  addiu      $a2, $a2, -0x20
    /* CDB00 800CCF00 ACA2001C */  sw         $v0, 0x1C($a1)
    /* CDB04 800CCF04 ACA30018 */  sw         $v1, 0x18($a1)
    /* CDB08 800CCF08 ACA80014 */  sw         $t0, 0x14($a1)
    /* CDB0C 800CCF0C ACA90010 */  sw         $t1, 0x10($a1)
    /* CDB10 800CCF10 ACAA000C */  sw         $t2, 0xC($a1)
    /* CDB14 800CCF14 ACAB0008 */  sw         $t3, 0x8($a1)
    /* CDB18 800CCF18 ACAC0004 */  sw         $t4, 0x4($a1)
    /* CDB1C 800CCF1C 1000FFEA */  b          .L800CCEC8
    /* CDB20 800CCF20 ACAD0000 */   sw        $t5, 0x0($a1)
  .L800CCF24:
    /* CDB24 800CCF24 28C10010 */  slti       $at, $a2, 0x10
  .L800CCF28:
    /* CDB28 800CCF28 5420000E */  bnel       $at, $zero, .L800CCF64
    /* CDB2C 800CCF2C 28C10004 */   slti      $at, $a2, 0x4
    /* CDB30 800CCF30 8C82FFFC */  lw         $v0, -0x4($a0)
    /* CDB34 800CCF34 8C83FFF8 */  lw         $v1, -0x8($a0)
    /* CDB38 800CCF38 8C88FFF4 */  lw         $t0, -0xC($a0)
    /* CDB3C 800CCF3C 8C89FFF0 */  lw         $t1, -0x10($a0)
    /* CDB40 800CCF40 2484FFF0 */  addiu      $a0, $a0, -0x10
    /* CDB44 800CCF44 24A5FFF0 */  addiu      $a1, $a1, -0x10
    /* CDB48 800CCF48 24C6FFF0 */  addiu      $a2, $a2, -0x10
    /* CDB4C 800CCF4C ACA2000C */  sw         $v0, 0xC($a1)
    /* CDB50 800CCF50 ACA30008 */  sw         $v1, 0x8($a1)
    /* CDB54 800CCF54 ACA80004 */  sw         $t0, 0x4($a1)
    /* CDB58 800CCF58 1000FFF2 */  b          .L800CCF24
    /* CDB5C 800CCF5C ACA90000 */   sw        $t1, 0x0($a1)
  .L800CCF60:
    /* CDB60 800CCF60 28C10004 */  slti       $at, $a2, 0x4
  .L800CCF64:
    /* CDB64 800CCF64 1420FFB3 */  bnez       $at, .L800CCE34
    /* CDB68 800CCF68 00000000 */   nop
    /* CDB6C 800CCF6C 8C82FFFC */  lw         $v0, -0x4($a0)
    /* CDB70 800CCF70 2484FFFC */  addiu      $a0, $a0, -0x4
    /* CDB74 800CCF74 24A5FFFC */  addiu      $a1, $a1, -0x4
    /* CDB78 800CCF78 24C6FFFC */  addiu      $a2, $a2, -0x4
    /* CDB7C 800CCF7C 1000FFF8 */  b          .L800CCF60
    /* CDB80 800CCF80 ACA20000 */   sw        $v0, 0x0($a1)
endlabel bcopy
    /* CDB84 800CCF84 00000000 */  nop
    /* CDB88 800CCF88 00000000 */  nop
    /* CDB8C 800CCF8C 00000000 */  nop
