.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */


glabel bzero
    /* D5230 800D4630 28A1000C */  slti       $at, $a1, 0xC
    /* D5234 800D4634 1420001D */  bnez       $at, .L800D46AC
    /* D5238 800D4638 00041823 */   negu      $v1, $a0
    /* D523C 800D463C 30630003 */  andi       $v1, $v1, 0x3
    /* D5240 800D4640 10600003 */  beqz       $v1, .L800D4650
    /* D5244 800D4644 00A32823 */   subu      $a1, $a1, $v1
    /* D5248 800D4648 A8800000 */  swl        $zero, 0x0($a0)
    /* D524C 800D464C 00832021 */  addu       $a0, $a0, $v1
  .L800D4650:
    /* D5250 800D4650 2401FFE0 */  addiu      $at, $zero, -0x20
    /* D5254 800D4654 00A13824 */  and        $a3, $a1, $at
    /* D5258 800D4658 10E0000C */  beqz       $a3, .L800D468C
    /* D525C 800D465C 00A72823 */   subu      $a1, $a1, $a3
    /* D5260 800D4660 00E43821 */  addu       $a3, $a3, $a0
  .L800D4664:
    /* D5264 800D4664 24840020 */  addiu      $a0, $a0, 0x20
    /* D5268 800D4668 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* D526C 800D466C AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* D5270 800D4670 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* D5274 800D4674 AC80FFEC */  sw         $zero, -0x14($a0)
    /* D5278 800D4678 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* D527C 800D467C AC80FFF4 */  sw         $zero, -0xC($a0)
    /* D5280 800D4680 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* D5284 800D4684 1487FFF7 */  bne        $a0, $a3, .L800D4664
    /* D5288 800D4688 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800D468C:
    /* D528C 800D468C 2401FFFC */  addiu      $at, $zero, -0x4
    /* D5290 800D4690 00A13824 */  and        $a3, $a1, $at
    /* D5294 800D4694 10E00005 */  beqz       $a3, .L800D46AC
    /* D5298 800D4698 00A72823 */   subu      $a1, $a1, $a3
    /* D529C 800D469C 00E43821 */  addu       $a3, $a3, $a0
  .L800D46A0:
    /* D52A0 800D46A0 24840004 */  addiu      $a0, $a0, 0x4
    /* D52A4 800D46A4 1487FFFE */  bne        $a0, $a3, .L800D46A0
    /* D52A8 800D46A8 AC80FFFC */   sw        $zero, -0x4($a0)
  .L800D46AC:
    /* D52AC 800D46AC 18A00005 */  blez       $a1, .L800D46C4
    /* D52B0 800D46B0 00000000 */   nop
    /* D52B4 800D46B4 00A42821 */  addu       $a1, $a1, $a0
  .L800D46B8:
    /* D52B8 800D46B8 24840001 */  addiu      $a0, $a0, 0x1
    /* D52BC 800D46BC 1485FFFE */  bne        $a0, $a1, .L800D46B8
    /* D52C0 800D46C0 A080FFFF */   sb        $zero, -0x1($a0)
  .L800D46C4:
    /* D52C4 800D46C4 03E00008 */  jr         $ra
    /* D52C8 800D46C8 00000000 */   nop
endlabel bzero
    /* D52CC 800D46CC 00000000 */  nop
