.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel __osExceptionPreamble
    /* CCF70 800CC370 3C1A800D */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* CCF74 800CC374 275AC380 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* CCF78 800CC378 03400008 */  jr         $k0
    /* CCF7C 800CC37C 00000000 */   nop
endlabel __osExceptionPreamble

/* Handwritten function */

glabel __osException
    /* CCF80 800CC380 3C1A801B */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* CCF84 800CC384 275A1E70 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* CCF88 800CC388 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* CCF8C 800CC38C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* CCF90 800CC390 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* CCF94 800CC394 2401FFFC */  addiu      $at, $zero, -0x4
    /* CCF98 800CC398 0361D824 */  and        $k1, $k1, $at
    /* CCF9C 800CC39C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* CCFA0 800CC3A0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* CCFA4 800CC3A4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* CCFA8 800CC3A8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* CCFAC 800CC3AC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* CCFB0 800CC3B0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* CCFB4 800CC3B4 03404025 */  or         $t0, $k0, $zero
    /* CCFB8 800CC3B8 3C1A800F */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* CCFBC 800CC3BC 8F5ACD10 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* CCFC0 800CC3C0 DD090020 */  ld         $t1, 0x20($t0)
    /* CCFC4 800CC3C4 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* CCFC8 800CC3C8 DD090118 */  ld         $t1, 0x118($t0)
    /* CCFCC 800CC3CC FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* CCFD0 800CC3D0 DD090058 */  ld         $t1, 0x58($t0)
    /* CCFD4 800CC3D4 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* CCFD8 800CC3D8 DD090060 */  ld         $t1, 0x60($t0)
    /* CCFDC 800CC3DC FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* CCFE0 800CC3E0 DD090068 */  ld         $t1, 0x68($t0)
    /* CCFE4 800CC3E4 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* CCFE8 800CC3E8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* CCFEC 800CC3EC 00004012 */  mflo       $t0
    /* CCFF0 800CC3F0 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* CCFF4 800CC3F4 00004010 */  mfhi       $t0
    /* CCFF8 800CC3F8 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* CCFFC 800CC3FC FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* CD000 800CC400 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* CD004 800CC404 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* CD008 800CC408 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* CD00C 800CC40C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* CD010 800CC410 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* CD014 800CC414 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* CD018 800CC418 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* CD01C 800CC41C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* CD020 800CC420 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* CD024 800CC424 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* CD028 800CC428 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* CD02C 800CC42C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* CD030 800CC430 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* CD034 800CC434 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* CD038 800CC438 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* CD03C 800CC43C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* CD040 800CC440 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* CD044 800CC444 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* CD048 800CC448 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* CD04C 800CC44C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* CD050 800CC450 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* CD054 800CC454 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* CD058 800CC458 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* CD05C 800CC45C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* CD060 800CC460 1120000D */  beqz       $t1, .L800CC498
    /* CD064 800CC464 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* CD068 800CC468 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* CD06C 800CC46C 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* CD070 800CC470 8D080000 */  lw         $t0, 0x0($t0)
    /* CD074 800CC474 2401FFFF */  addiu      $at, $zero, -0x1
    /* CD078 800CC478 01014026 */  xor        $t0, $t0, $at
    /* CD07C 800CC47C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* CD080 800CC480 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* CD084 800CC484 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* CD088 800CC488 01284825 */  or         $t1, $t1, $t0
    /* CD08C 800CC48C 0361D824 */  and        $k1, $k1, $at
    /* CD090 800CC490 0369D825 */  or         $k1, $k1, $t1
    /* CD094 800CC494 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
  .L800CC498:
    /* CD098 800CC498 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* CD09C 800CC49C 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* CD0A0 800CC4A0 1120000B */  beqz       $t1, .L800CC4D0
    /* CD0A4 800CC4A4 00000000 */   nop
    /* CD0A8 800CC4A8 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* CD0AC 800CC4AC 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* CD0B0 800CC4B0 8D080000 */  lw         $t0, 0x0($t0)
    /* CD0B4 800CC4B4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* CD0B8 800CC4B8 2401FFFF */  addiu      $at, $zero, -0x1
    /* CD0BC 800CC4BC 00084402 */  srl        $t0, $t0, 16
    /* CD0C0 800CC4C0 01014026 */  xor        $t0, $t0, $at
    /* CD0C4 800CC4C4 3108003F */  andi       $t0, $t0, 0x3F
    /* CD0C8 800CC4C8 010C4024 */  and        $t0, $t0, $t4
    /* CD0CC 800CC4CC 01284825 */  or         $t1, $t1, $t0
  .L800CC4D0:
    /* CD0D0 800CC4D0 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* CD0D4 800CC4D4 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* CD0D8 800CC4D8 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* CD0DC 800CC4DC 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* CD0E0 800CC4E0 11000014 */  beqz       $t0, .L800CC534
    /* CD0E4 800CC4E4 00000000 */   nop
    /* CD0E8 800CC4E8 4448F800 */  cfc1       $t0, $31
    /* CD0EC 800CC4EC 00000000 */  nop
    /* CD0F0 800CC4F0 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* CD0F4 800CC4F4 F7400130 */  sdc1       $fv0, 0x130($k0)
    /* CD0F8 800CC4F8 F7420138 */  sdc1       $fv1, 0x138($k0)
    /* CD0FC 800CC4FC F7440140 */  sdc1       $ft0, 0x140($k0)
    /* CD100 800CC500 F7460148 */  sdc1       $ft1, 0x148($k0)
    /* CD104 800CC504 F7480150 */  sdc1       $ft2, 0x150($k0)
    /* CD108 800CC508 F74A0158 */  sdc1       $ft3, 0x158($k0)
    /* CD10C 800CC50C F74C0160 */  sdc1       $fa0, 0x160($k0)
    /* CD110 800CC510 F74E0168 */  sdc1       $fa1, 0x168($k0)
    /* CD114 800CC514 F7500170 */  sdc1       $ft4, 0x170($k0)
    /* CD118 800CC518 F7520178 */  sdc1       $ft5, 0x178($k0)
    /* CD11C 800CC51C F7540180 */  sdc1       $fs0, 0x180($k0)
    /* CD120 800CC520 F7560188 */  sdc1       $fs1, 0x188($k0)
    /* CD124 800CC524 F7580190 */  sdc1       $fs2, 0x190($k0)
    /* CD128 800CC528 F75A0198 */  sdc1       $fs3, 0x198($k0)
    /* CD12C 800CC52C F75C01A0 */  sdc1       $fs4, 0x1A0($k0)
    /* CD130 800CC530 F75E01A8 */  sdc1       $fs5, 0x1A8($k0)
  .L800CC534:
    /* CD134 800CC534 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* CD138 800CC538 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* CD13C 800CC53C 24090002 */  addiu      $t1, $zero, 0x2
    /* CD140 800CC540 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* CD144 800CC544 3109007C */  andi       $t1, $t0, 0x7C
    /* CD148 800CC548 240A0024 */  addiu      $t2, $zero, 0x24
    /* CD14C 800CC54C 112A00B0 */  beq        $t1, $t2, .L800CC810
    /* CD150 800CC550 00000000 */   nop
    /* CD154 800CC554 240A002C */  addiu      $t2, $zero, 0x2C
    /* CD158 800CC558 112A00FF */  beq        $t1, $t2, .L800CC958
    /* CD15C 800CC55C 00000000 */   nop
    /* CD160 800CC560 240A0000 */  addiu      $t2, $zero, 0x0
    /* CD164 800CC564 152A00C3 */  bne        $t1, $t2, .L800CC874
    /* CD168 800CC568 00000000 */   nop
    /* CD16C 800CC56C 03688024 */  and        $s0, $k1, $t0
  .L800CC570:
    /* CD170 800CC570 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* CD174 800CC574 00095302 */  srl        $t2, $t1, 12
    /* CD178 800CC578 15400003 */  bnez       $t2, .L800CC588
    /* CD17C 800CC57C 00000000 */   nop
    /* CD180 800CC580 00095202 */  srl        $t2, $t1, 8
    /* CD184 800CC584 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L800CC588:
    /* CD188 800CC588 3C01800F */  lui        $at, %hi(__osIntOffTable)
    /* CD18C 800CC58C 002A0821 */  addu       $at, $at, $t2
    /* CD190 800CC590 902A0260 */  lbu        $t2, %lo(__osIntOffTable)($at)
    /* CD194 800CC594 3C01800F */  lui        $at, %hi(__osIntTable)
    /* CD198 800CC598 002A0821 */  addu       $at, $at, $t2
    /* CD19C 800CC59C 8C2A0280 */  lw         $t2, %lo(__osIntTable)($at)
    /* CD1A0 800CC5A0 01400008 */  jr         $t2
    /* CD1A4 800CC5A4 00000000 */   nop
  jlabel .L800CC5A8
    /* CD1A8 800CC5A8 2401DFFF */  addiu      $at, $zero, -0x2001
    /* CD1AC 800CC5AC 1000FFF0 */  b          .L800CC570
    /* CD1B0 800CC5B0 02018024 */   and       $s0, $s0, $at
  jlabel .L800CC5B4
    /* CD1B4 800CC5B4 2401BFFF */  addiu      $at, $zero, -0x4001
    /* CD1B8 800CC5B8 1000FFED */  b          .L800CC570
    /* CD1BC 800CC5BC 02018024 */   and       $s0, $s0, $at
  jlabel .L800CC5C0
    /* CD1C0 800CC5C0 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* CD1C4 800CC5C4 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* CD1C8 800CC5C8 0C033229 */  jal        send_mesg
    /* CD1CC 800CC5CC 24040018 */   addiu     $a0, $zero, 0x18
    /* CD1D0 800CC5D0 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* CD1D4 800CC5D4 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* CD1D8 800CC5D8 1000FFE5 */  b          .L800CC570
    /* CD1DC 800CC5DC 02018024 */   and       $s0, $s0, $at
  jlabel .L800CC5E0
    /* CD1E0 800CC5E0 2401F7FF */  addiu      $at, $zero, -0x801
    /* CD1E4 800CC5E4 02018024 */  and        $s0, $s0, $at
    /* CD1E8 800CC5E8 240A0004 */  addiu      $t2, $zero, 0x4
    /* CD1EC 800CC5EC 3C01800F */  lui        $at, %hi(__osHwIntTable)
    /* CD1F0 800CC5F0 002A0821 */  addu       $at, $at, $t2
    /* CD1F4 800CC5F4 8C2ACD20 */  lw         $t2, %lo(__osHwIntTable)($at)
    /* CD1F8 800CC5F8 3C1D801B */  lui        $sp, %hi(leoDiskStack)
    /* CD1FC 800CC5FC 27BD0E50 */  addiu      $sp, $sp, %lo(leoDiskStack)
    /* CD200 800CC600 24040010 */  addiu      $a0, $zero, 0x10
    /* CD204 800CC604 11400007 */  beqz       $t2, .L800CC624
    /* CD208 800CC608 27BD0FF0 */   addiu     $sp, $sp, 0xFF0
    /* CD20C 800CC60C 0140F809 */  jalr       $t2
    /* CD210 800CC610 00000000 */   nop
    /* CD214 800CC614 10400003 */  beqz       $v0, .L800CC624
    /* CD218 800CC618 00000000 */   nop
    /* CD21C 800CC61C 10000082 */  b          .L800CC828
    /* CD220 800CC620 00000000 */   nop
  .L800CC624:
    /* CD224 800CC624 0C033229 */  jal        send_mesg
    /* CD228 800CC628 00000000 */   nop
    /* CD22C 800CC62C 1000FFD0 */  b          .L800CC570
    /* CD230 800CC630 00000000 */   nop
  jlabel .L800CC634
    /* CD234 800CC634 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* CD238 800CC638 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* CD23C 800CC63C 8D080000 */  lw         $t0, 0x0($t0)
    /* CD240 800CC640 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* CD244 800CC644 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* CD248 800CC648 00084402 */  srl        $t0, $t0, 16
    /* CD24C 800CC64C 02288824 */  and        $s1, $s1, $t0
    /* CD250 800CC650 32290001 */  andi       $t1, $s1, 0x1
    /* CD254 800CC654 11200013 */  beqz       $t1, .L800CC6A4
    /* CD258 800CC658 00000000 */   nop
    /* CD25C 800CC65C 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* CD260 800CC660 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* CD264 800CC664 24090008 */  addiu      $t1, $zero, 0x8
    /* CD268 800CC668 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* CD26C 800CC66C 318C0300 */  andi       $t4, $t4, 0x300
    /* CD270 800CC670 3231003E */  andi       $s1, $s1, 0x3E
    /* CD274 800CC674 11800007 */  beqz       $t4, .L800CC694
    /* CD278 800CC678 AC290010 */   sw        $t1, %lo(D_A4040010)($at)
    /* CD27C 800CC67C 0C033229 */  jal        send_mesg
    /* CD280 800CC680 24040020 */   addiu     $a0, $zero, 0x20
    /* CD284 800CC684 12200038 */  beqz       $s1, .L800CC768
    /* CD288 800CC688 00000000 */   nop
    /* CD28C 800CC68C 10000005 */  b          .L800CC6A4
    /* CD290 800CC690 00000000 */   nop
  .L800CC694:
    /* CD294 800CC694 0C033229 */  jal        send_mesg
    /* CD298 800CC698 24040058 */   addiu     $a0, $zero, 0x58
    /* CD29C 800CC69C 12200032 */  beqz       $s1, .L800CC768
    /* CD2A0 800CC6A0 00000000 */   nop
  .L800CC6A4:
    /* CD2A4 800CC6A4 32290008 */  andi       $t1, $s1, 0x8
    /* CD2A8 800CC6A8 11200007 */  beqz       $t1, .L800CC6C8
    /* CD2AC 800CC6AC 3C01A440 */   lui       $at, %hi(D_A4400010)
    /* CD2B0 800CC6B0 32310037 */  andi       $s1, $s1, 0x37
    /* CD2B4 800CC6B4 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* CD2B8 800CC6B8 0C033229 */  jal        send_mesg
    /* CD2BC 800CC6BC 24040038 */   addiu     $a0, $zero, 0x38
    /* CD2C0 800CC6C0 12200029 */  beqz       $s1, .L800CC768
    /* CD2C4 800CC6C4 00000000 */   nop
  .L800CC6C8:
    /* CD2C8 800CC6C8 32290004 */  andi       $t1, $s1, 0x4
    /* CD2CC 800CC6CC 11200009 */  beqz       $t1, .L800CC6F4
    /* CD2D0 800CC6D0 00000000 */   nop
    /* CD2D4 800CC6D4 24090001 */  addiu      $t1, $zero, 0x1
    /* CD2D8 800CC6D8 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* CD2DC 800CC6DC 3231003B */  andi       $s1, $s1, 0x3B
    /* CD2E0 800CC6E0 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* CD2E4 800CC6E4 0C033229 */  jal        send_mesg
    /* CD2E8 800CC6E8 24040030 */   addiu     $a0, $zero, 0x30
    /* CD2EC 800CC6EC 1220001E */  beqz       $s1, .L800CC768
    /* CD2F0 800CC6F0 00000000 */   nop
  .L800CC6F4:
    /* CD2F4 800CC6F4 32290002 */  andi       $t1, $s1, 0x2
    /* CD2F8 800CC6F8 11200007 */  beqz       $t1, .L800CC718
    /* CD2FC 800CC6FC 3C01A480 */   lui       $at, %hi(D_A4800018)
    /* CD300 800CC700 3231003D */  andi       $s1, $s1, 0x3D
    /* CD304 800CC704 AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* CD308 800CC708 0C033229 */  jal        send_mesg
    /* CD30C 800CC70C 24040028 */   addiu     $a0, $zero, 0x28
    /* CD310 800CC710 12200015 */  beqz       $s1, .L800CC768
    /* CD314 800CC714 00000000 */   nop
  .L800CC718:
    /* CD318 800CC718 32290010 */  andi       $t1, $s1, 0x10
    /* CD31C 800CC71C 11200009 */  beqz       $t1, .L800CC744
    /* CD320 800CC720 00000000 */   nop
    /* CD324 800CC724 24090002 */  addiu      $t1, $zero, 0x2
    /* CD328 800CC728 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* CD32C 800CC72C 3231002F */  andi       $s1, $s1, 0x2F
    /* CD330 800CC730 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* CD334 800CC734 0C033229 */  jal        send_mesg
    /* CD338 800CC738 24040040 */   addiu     $a0, $zero, 0x40
    /* CD33C 800CC73C 1220000A */  beqz       $s1, .L800CC768
    /* CD340 800CC740 00000000 */   nop
  .L800CC744:
    /* CD344 800CC744 32290020 */  andi       $t1, $s1, 0x20
    /* CD348 800CC748 11200007 */  beqz       $t1, .L800CC768
    /* CD34C 800CC74C 00000000 */   nop
    /* CD350 800CC750 24090800 */  addiu      $t1, $zero, 0x800
    /* CD354 800CC754 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* CD358 800CC758 3231001F */  andi       $s1, $s1, 0x1F
    /* CD35C 800CC75C AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* CD360 800CC760 0C033229 */  jal        send_mesg
    /* CD364 800CC764 24040048 */   addiu     $a0, $zero, 0x48
  .L800CC768:
    /* CD368 800CC768 2401FBFF */  addiu      $at, $zero, -0x401
    /* CD36C 800CC76C 1000FF80 */  b          .L800CC570
    /* CD370 800CC770 02018024 */   and       $s0, $s0, $at
  jlabel .L800CC774
    /* CD374 800CC774 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* CD378 800CC778 2401EFFF */  addiu      $at, $zero, -0x1001
    /* CD37C 800CC77C 3C09800F */  lui        $t1, %hi(D_800ECC48)
    /* CD380 800CC780 0361D824 */  and        $k1, $k1, $at
    /* CD384 800CC784 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* CD388 800CC788 2529CC48 */  addiu      $t1, $t1, %lo(D_800ECC48)
    /* CD38C 800CC78C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* CD390 800CC790 11400003 */  beqz       $t2, .L800CC7A0
    /* CD394 800CC794 2401EFFF */   addiu     $at, $zero, -0x1001
    /* CD398 800CC798 10000023 */  b          .L800CC828
    /* CD39C 800CC79C 02018024 */   and       $s0, $s0, $at
  .L800CC7A0:
    /* CD3A0 800CC7A0 240A0001 */  addiu      $t2, $zero, 0x1
    /* CD3A4 800CC7A4 AD2A0000 */  sw         $t2, 0x0($t1)
    /* CD3A8 800CC7A8 0C033229 */  jal        send_mesg
    /* CD3AC 800CC7AC 24040070 */   addiu     $a0, $zero, 0x70
    /* CD3B0 800CC7B0 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* CD3B4 800CC7B4 8D4ACD08 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* CD3B8 800CC7B8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* CD3BC 800CC7BC 02018024 */  and        $s0, $s0, $at
    /* CD3C0 800CC7C0 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* CD3C4 800CC7C4 0361D824 */  and        $k1, $k1, $at
    /* CD3C8 800CC7C8 10000017 */  b          .L800CC828
    /* CD3CC 800CC7CC AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .L800CC7D0
    /* CD3D0 800CC7D0 2401FDFF */  addiu      $at, $zero, -0x201
    /* CD3D4 800CC7D4 01014024 */  and        $t0, $t0, $at
    /* CD3D8 800CC7D8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* CD3DC 800CC7DC 0C033229 */  jal        send_mesg
    /* CD3E0 800CC7E0 24040008 */   addiu     $a0, $zero, 0x8
    /* CD3E4 800CC7E4 2401FDFF */  addiu      $at, $zero, -0x201
    /* CD3E8 800CC7E8 1000FF61 */  b          .L800CC570
    /* CD3EC 800CC7EC 02018024 */   and       $s0, $s0, $at
  jlabel .L800CC7F0
    /* CD3F0 800CC7F0 2401FEFF */  addiu      $at, $zero, -0x101
    /* CD3F4 800CC7F4 01014024 */  and        $t0, $t0, $at
    /* CD3F8 800CC7F8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* CD3FC 800CC7FC 0C033229 */  jal        send_mesg
    /* CD400 800CC800 24040000 */   addiu     $a0, $zero, 0x0
    /* CD404 800CC804 2401FEFF */  addiu      $at, $zero, -0x101
    /* CD408 800CC808 1000FF59 */  b          .L800CC570
    /* CD40C 800CC80C 02018024 */   and       $s0, $s0, $at
  .L800CC810:
    /* CD410 800CC810 24090001 */  addiu      $t1, $zero, 0x1
    /* CD414 800CC814 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* CD418 800CC818 0C033229 */  jal        send_mesg
    /* CD41C 800CC81C 24040050 */   addiu     $a0, $zero, 0x50
    /* CD420 800CC820 10000001 */  b          .L800CC828
    /* CD424 800CC824 00000000 */   nop
  jlabel .L800CC828
    /* CD428 800CC828 3C0A800F */  lui        $t2, %hi(__osRunQueue)
    /* CD42C 800CC82C 8D4ACD08 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* CD430 800CC830 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* CD434 800CC834 8D4B0004 */  lw         $t3, 0x4($t2)
    /* CD438 800CC838 012B082A */  slt        $at, $t1, $t3
    /* CD43C 800CC83C 10200007 */  beqz       $at, .L800CC85C
    /* CD440 800CC840 00000000 */   nop
    /* CD444 800CC844 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* CD448 800CC848 03402825 */  or         $a1, $k0, $zero
    /* CD44C 800CC84C 0C0332A3 */  jal        __osEnqueueThread
    /* CD450 800CC850 2484CD08 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* CD454 800CC854 080332B9 */  j          __osDispatchThread
    /* CD458 800CC858 00000000 */   nop
  .L800CC85C:
    /* CD45C 800CC85C 3C09800F */  lui        $t1, %hi(__osRunQueue)
    /* CD460 800CC860 2529CD08 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* CD464 800CC864 8D2A0000 */  lw         $t2, 0x0($t1)
    /* CD468 800CC868 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* CD46C 800CC86C 080332B9 */  j          __osDispatchThread
    /* CD470 800CC870 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L800CC874:
    /* CD474 800CC874 3C01800F */  lui        $at, %hi(__osFaultedThread)
    /* CD478 800CC878 AC3ACD14 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* CD47C 800CC87C 24090001 */  addiu      $t1, $zero, 0x1
    /* CD480 800CC880 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* CD484 800CC884 24090002 */  addiu      $t1, $zero, 0x2
    /* CD488 800CC888 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* CD48C 800CC88C 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* CD490 800CC890 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* CD494 800CC894 0C033229 */  jal        send_mesg
    /* CD498 800CC898 24040060 */   addiu     $a0, $zero, 0x60
    /* CD49C 800CC89C 080332B9 */  j          __osDispatchThread
    /* CD4A0 800CC8A0 00000000 */   nop
endlabel __osException

/* Handwritten function */

glabel send_mesg
    /* CD4A4 800CC8A4 3C0A801B */  lui        $t2, %hi(__osEventStateTab)
    /* CD4A8 800CC8A8 254AFA80 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* CD4AC 800CC8AC 01445021 */  addu       $t2, $t2, $a0
    /* CD4B0 800CC8B0 8D490000 */  lw         $t1, 0x0($t2)
    /* CD4B4 800CC8B4 03E09025 */  or         $s2, $ra, $zero
    /* CD4B8 800CC8B8 11200025 */  beqz       $t1, .L800CC950
    /* CD4BC 800CC8BC 00000000 */   nop
    /* CD4C0 800CC8C0 8D2B0008 */  lw         $t3, 0x8($t1)
    /* CD4C4 800CC8C4 8D2C0010 */  lw         $t4, 0x10($t1)
    /* CD4C8 800CC8C8 016C082A */  slt        $at, $t3, $t4
    /* CD4CC 800CC8CC 10200020 */  beqz       $at, .L800CC950
    /* CD4D0 800CC8D0 00000000 */   nop
    /* CD4D4 800CC8D4 8D2D000C */  lw         $t5, 0xC($t1)
    /* CD4D8 800CC8D8 01AB6821 */  addu       $t5, $t5, $t3
    /* CD4DC 800CC8DC 01AC001A */  div        $zero, $t5, $t4
    /* CD4E0 800CC8E0 15800002 */  bnez       $t4, .L800CC8EC
    /* CD4E4 800CC8E4 00000000 */   nop
    /* CD4E8 800CC8E8 0007000D */  break      7
  .L800CC8EC:
    /* CD4EC 800CC8EC 2401FFFF */  addiu      $at, $zero, -0x1
    /* CD4F0 800CC8F0 15810004 */  bne        $t4, $at, .L800CC904
    /* CD4F4 800CC8F4 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* CD4F8 800CC8F8 15A10002 */  bne        $t5, $at, .L800CC904
    /* CD4FC 800CC8FC 00000000 */   nop
    /* CD500 800CC900 0006000D */  break      6
  .L800CC904:
    /* CD504 800CC904 8D2C0014 */  lw         $t4, 0x14($t1)
    /* CD508 800CC908 00006810 */  mfhi       $t5
    /* CD50C 800CC90C 000D6880 */  sll        $t5, $t5, 2
    /* CD510 800CC910 018D6021 */  addu       $t4, $t4, $t5
    /* CD514 800CC914 8D4D0004 */  lw         $t5, 0x4($t2)
    /* CD518 800CC918 256A0001 */  addiu      $t2, $t3, 0x1
    /* CD51C 800CC91C AD8D0000 */  sw         $t5, 0x0($t4)
    /* CD520 800CC920 AD2A0008 */  sw         $t2, 0x8($t1)
    /* CD524 800CC924 8D2A0000 */  lw         $t2, 0x0($t1)
    /* CD528 800CC928 8D4B0000 */  lw         $t3, 0x0($t2)
    /* CD52C 800CC92C 11600008 */  beqz       $t3, .L800CC950
    /* CD530 800CC930 00000000 */   nop
    /* CD534 800CC934 0C0332B5 */  jal        __osPopThread
    /* CD538 800CC938 01202025 */   or        $a0, $t1, $zero
    /* CD53C 800CC93C 00405025 */  or         $t2, $v0, $zero
    /* CD540 800CC940 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* CD544 800CC944 01402825 */  or         $a1, $t2, $zero
    /* CD548 800CC948 0C0332A3 */  jal        __osEnqueueThread
    /* CD54C 800CC94C 2484CD08 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L800CC950:
    /* CD550 800CC950 02400008 */  jr         $s2
    /* CD554 800CC954 00000000 */   nop
  .L800CC958:
    /* CD558 800CC958 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* CD55C 800CC95C 01014824 */  and        $t1, $t0, $at
    /* CD560 800CC960 00094F02 */  srl        $t1, $t1, 28
    /* CD564 800CC964 240A0001 */  addiu      $t2, $zero, 0x1
    /* CD568 800CC968 152AFFC2 */  bne        $t1, $t2, .L800CC874
    /* CD56C 800CC96C 00000000 */   nop
    /* CD570 800CC970 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* CD574 800CC974 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* CD578 800CC978 24090001 */  addiu      $t1, $zero, 0x1
    /* CD57C 800CC97C 0361D825 */  or         $k1, $k1, $at
    /* CD580 800CC980 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* CD584 800CC984 1000FFB5 */  b          .L800CC85C
    /* CD588 800CC988 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
endlabel send_mesg

/* Handwritten function */

glabel __osEnqueueAndYield
    /* CD58C 800CC98C 3C05800F */  lui        $a1, %hi(__osRunningThread)
    /* CD590 800CC990 8CA5CD10 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* CD594 800CC994 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* CD598 800CC998 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* CD59C 800CC99C 35080002 */  ori        $t0, $t0, 0x2
    /* CD5A0 800CC9A0 ACA80118 */  sw         $t0, 0x118($a1)
    /* CD5A4 800CC9A4 FCB00098 */  sd         $s0, 0x98($a1)
    /* CD5A8 800CC9A8 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* CD5AC 800CC9AC FCB200A8 */  sd         $s2, 0xA8($a1)
    /* CD5B0 800CC9B0 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* CD5B4 800CC9B4 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* CD5B8 800CC9B8 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* CD5BC 800CC9BC FCB600C8 */  sd         $s6, 0xC8($a1)
    /* CD5C0 800CC9C0 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* CD5C4 800CC9C4 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* CD5C8 800CC9C8 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* CD5CC 800CC9CC FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* CD5D0 800CC9D0 FCBF0100 */  sd         $ra, 0x100($a1)
    /* CD5D4 800CC9D4 13600009 */  beqz       $k1, .L800CC9FC /* handwritten instruction */
    /* CD5D8 800CC9D8 ACBF011C */   sw        $ra, 0x11C($a1)
    /* CD5DC 800CC9DC 445BF800 */  cfc1       $k1, $31
    /* CD5E0 800CC9E0 F4B40180 */  sdc1       $fs0, 0x180($a1)
    /* CD5E4 800CC9E4 F4B60188 */  sdc1       $fs1, 0x188($a1)
    /* CD5E8 800CC9E8 F4B80190 */  sdc1       $fs2, 0x190($a1)
    /* CD5EC 800CC9EC F4BA0198 */  sdc1       $fs3, 0x198($a1)
    /* CD5F0 800CC9F0 F4BC01A0 */  sdc1       $fs4, 0x1A0($a1)
    /* CD5F4 800CC9F4 F4BE01A8 */  sdc1       $fs5, 0x1A8($a1)
    /* CD5F8 800CC9F8 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L800CC9FC:
    /* CD5FC 800CC9FC 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* CD600 800CCA00 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* CD604 800CCA04 1120000D */  beqz       $t1, .L800CCA3C
    /* CD608 800CCA08 00000000 */   nop
    /* CD60C 800CCA0C 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* CD610 800CCA10 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* CD614 800CCA14 8D080000 */  lw         $t0, 0x0($t0)
    /* CD618 800CCA18 2401FFFF */  addiu      $at, $zero, -0x1
    /* CD61C 800CCA1C 01014026 */  xor        $t0, $t0, $at
    /* CD620 800CCA20 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* CD624 800CCA24 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* CD628 800CCA28 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* CD62C 800CCA2C 01284825 */  or         $t1, $t1, $t0
    /* CD630 800CCA30 0361D824 */  and        $k1, $k1, $at
    /* CD634 800CCA34 0369D825 */  or         $k1, $k1, $t1
    /* CD638 800CCA38 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L800CCA3C:
    /* CD63C 800CCA3C 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* CD640 800CCA40 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* CD644 800CCA44 1360000B */  beqz       $k1, .L800CCA74 /* handwritten instruction */
    /* CD648 800CCA48 00000000 */   nop
    /* CD64C 800CCA4C 3C1A800F */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* CD650 800CCA50 275ACC4C */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* CD654 800CCA54 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* CD658 800CCA58 8CA80128 */  lw         $t0, 0x128($a1)
    /* CD65C 800CCA5C 2401FFFF */  addiu      $at, $zero, -0x1
    /* CD660 800CCA60 001AD402 */  srl        $k0, $k0, 16
    /* CD664 800CCA64 0341D026 */  xor        $k0, $k0, $at
    /* CD668 800CCA68 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* CD66C 800CCA6C 0348D024 */  and        $k0, $k0, $t0
    /* CD670 800CCA70 037AD825 */  or         $k1, $k1, $k0
  .L800CCA74:
    /* CD674 800CCA74 10800003 */  beqz       $a0, .L800CCA84
    /* CD678 800CCA78 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* CD67C 800CCA7C 0C0332A3 */  jal        __osEnqueueThread
    /* CD680 800CCA80 00000000 */   nop
  .L800CCA84:
    /* CD684 800CCA84 080332B9 */  j          __osDispatchThread
    /* CD688 800CCA88 00000000 */   nop
endlabel __osEnqueueAndYield


glabel __osEnqueueThread
    /* CD68C 800CCA8C 8C980000 */  lw         $t8, 0x0($a0)
    /* CD690 800CCA90 8CAF0004 */  lw         $t7, 0x4($a1)
    /* CD694 800CCA94 0080C825 */  or         $t9, $a0, $zero
    /* CD698 800CCA98 8F0E0004 */  lw         $t6, 0x4($t8)
    /* CD69C 800CCA9C 01CF082A */  slt        $at, $t6, $t7
    /* CD6A0 800CCAA0 14200007 */  bnez       $at, .L800CCAC0
    /* CD6A4 800CCAA4 00000000 */   nop
  .L800CCAA8:
    /* CD6A8 800CCAA8 0300C825 */  or         $t9, $t8, $zero
    /* CD6AC 800CCAAC 8F180000 */  lw         $t8, 0x0($t8)
    /* CD6B0 800CCAB0 8F0E0004 */  lw         $t6, 0x4($t8)
    /* CD6B4 800CCAB4 01CF082A */  slt        $at, $t6, $t7
    /* CD6B8 800CCAB8 1020FFFB */  beqz       $at, .L800CCAA8
    /* CD6BC 800CCABC 00000000 */   nop
  .L800CCAC0:
    /* CD6C0 800CCAC0 8F380000 */  lw         $t8, 0x0($t9)
    /* CD6C4 800CCAC4 ACB80000 */  sw         $t8, 0x0($a1)
    /* CD6C8 800CCAC8 AF250000 */  sw         $a1, 0x0($t9)
    /* CD6CC 800CCACC 03E00008 */  jr         $ra
    /* CD6D0 800CCAD0 ACA40008 */   sw        $a0, 0x8($a1)
endlabel __osEnqueueThread


glabel __osPopThread
    /* CD6D4 800CCAD4 8C820000 */  lw         $v0, 0x0($a0)
    /* CD6D8 800CCAD8 8C590000 */  lw         $t9, 0x0($v0)
    /* CD6DC 800CCADC 03E00008 */  jr         $ra
    /* CD6E0 800CCAE0 AC990000 */   sw        $t9, 0x0($a0)
endlabel __osPopThread

/* Handwritten function */

glabel __osDispatchThread
    /* CD6E4 800CCAE4 3C04800F */  lui        $a0, %hi(__osRunQueue)
    /* CD6E8 800CCAE8 0C0332B5 */  jal        __osPopThread
    /* CD6EC 800CCAEC 2484CD08 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* CD6F0 800CCAF0 3C01800F */  lui        $at, %hi(__osRunningThread)
    /* CD6F4 800CCAF4 AC22CD10 */  sw         $v0, %lo(__osRunningThread)($at)
    /* CD6F8 800CCAF8 24080004 */  addiu      $t0, $zero, 0x4
    /* CD6FC 800CCAFC A4480010 */  sh         $t0, 0x10($v0)
    /* CD700 800CCB00 0040D025 */  or         $k0, $v0, $zero
    /* CD704 800CCB04 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* CD708 800CCB08 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* CD70C 800CCB0C 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* CD710 800CCB10 8D080000 */  lw         $t0, 0x0($t0)
    /* CD714 800CCB14 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* CD718 800CCB18 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* CD71C 800CCB1C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* CD720 800CCB20 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* CD724 800CCB24 01284824 */  and        $t1, $t1, $t0
    /* CD728 800CCB28 0361D824 */  and        $k1, $k1, $at
    /* CD72C 800CCB2C 0369D825 */  or         $k1, $k1, $t1
    /* CD730 800CCB30 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* CD734 800CCB34 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* CD738 800CCB38 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* CD73C 800CCB3C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* CD740 800CCB40 03600013 */  mtlo       $k1
    /* CD744 800CCB44 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* CD748 800CCB48 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* CD74C 800CCB4C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* CD750 800CCB50 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* CD754 800CCB54 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* CD758 800CCB58 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* CD75C 800CCB5C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* CD760 800CCB60 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* CD764 800CCB64 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* CD768 800CCB68 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* CD76C 800CCB6C DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* CD770 800CCB70 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* CD774 800CCB74 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* CD778 800CCB78 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* CD77C 800CCB7C DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* CD780 800CCB80 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* CD784 800CCB84 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* CD788 800CCB88 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* CD78C 800CCB8C DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* CD790 800CCB90 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* CD794 800CCB94 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* CD798 800CCB98 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* CD79C 800CCB9C DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* CD7A0 800CCBA0 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* CD7A4 800CCBA4 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* CD7A8 800CCBA8 03600011 */  mthi       $k1
    /* CD7AC 800CCBAC DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* CD7B0 800CCBB0 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* CD7B4 800CCBB4 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* CD7B8 800CCBB8 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* CD7BC 800CCBBC 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* CD7C0 800CCBC0 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* CD7C4 800CCBC4 13600013 */  beqz       $k1, .L800CCC14 /* handwritten instruction */
    /* CD7C8 800CCBC8 00000000 */   nop
    /* CD7CC 800CCBCC 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* CD7D0 800CCBD0 44DBF800 */  ctc1       $k1, $31
    /* CD7D4 800CCBD4 D7400130 */  ldc1       $fv0, 0x130($k0)
    /* CD7D8 800CCBD8 D7420138 */  ldc1       $fv1, 0x138($k0)
    /* CD7DC 800CCBDC D7440140 */  ldc1       $ft0, 0x140($k0)
    /* CD7E0 800CCBE0 D7460148 */  ldc1       $ft1, 0x148($k0)
    /* CD7E4 800CCBE4 D7480150 */  ldc1       $ft2, 0x150($k0)
    /* CD7E8 800CCBE8 D74A0158 */  ldc1       $ft3, 0x158($k0)
    /* CD7EC 800CCBEC D74C0160 */  ldc1       $fa0, 0x160($k0)
    /* CD7F0 800CCBF0 D74E0168 */  ldc1       $fa1, 0x168($k0)
    /* CD7F4 800CCBF4 D7500170 */  ldc1       $ft4, 0x170($k0)
    /* CD7F8 800CCBF8 D7520178 */  ldc1       $ft5, 0x178($k0)
    /* CD7FC 800CCBFC D7540180 */  ldc1       $fs0, 0x180($k0)
    /* CD800 800CCC00 D7560188 */  ldc1       $fs1, 0x188($k0)
    /* CD804 800CCC04 D7580190 */  ldc1       $fs2, 0x190($k0)
    /* CD808 800CCC08 D75A0198 */  ldc1       $fs3, 0x198($k0)
    /* CD80C 800CCC0C D75C01A0 */  ldc1       $fs4, 0x1A0($k0)
    /* CD810 800CCC10 D75E01A8 */  ldc1       $fs5, 0x1A8($k0)
  .L800CCC14:
    /* CD814 800CCC14 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* CD818 800CCC18 3C1A800F */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* CD81C 800CCC1C 275ACC4C */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* CD820 800CCC20 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* CD824 800CCC24 001AD402 */  srl        $k0, $k0, 16
    /* CD828 800CCC28 037AD824 */  and        $k1, $k1, $k0
    /* CD82C 800CCC2C 001BD840 */  sll        $k1, $k1, 1
    /* CD830 800CCC30 3C1A800F */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* CD834 800CCC34 275AFEE0 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* CD838 800CCC38 037AD821 */  addu       $k1, $k1, $k0
    /* CD83C 800CCC3C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* CD840 800CCC40 3C1AA430 */  lui        $k0, %hi(D_A430000C) /* handwritten instruction */
    /* CD844 800CCC44 275A000C */  addiu      $k0, $k0, %lo(D_A430000C) /* handwritten instruction */
    /* CD848 800CCC48 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* CD84C 800CCC4C 00000000 */  nop
    /* CD850 800CCC50 00000000 */  nop
    /* CD854 800CCC54 00000000 */  nop
    /* CD858 800CCC58 00000000 */  nop
    /* CD85C 800CCC5C 42000018 */  eret /* handwritten instruction */
endlabel __osDispatchThread


glabel __osCleanupThread
    /* CD860 800CCC60 0C032E10 */  jal        osDestroyThread
    /* CD864 800CCC64 00002025 */   or        $a0, $zero, $zero
endlabel __osCleanupThread

    /* CD868 800CCC68 00000000 */  nop
    /* CD86C 800CCC6C 00000000 */  nop

.section .rodata, "a"

dlabel __osIntOffTable
    .byte 0x00
    .byte 0x14
    .byte 0x18
    .byte 0x18
    .byte 0x1C
    .byte 0x1C
    .byte 0x1C
    .byte 0x1C
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x20
    .byte 0x00
    .byte 0x04
    .byte 0x08
    .byte 0x08
    .byte 0x0C
    .byte 0x0C
    .byte 0x0C
    .byte 0x0C
    .byte 0x10
    .byte 0x10
    .byte 0x10
    .byte 0x10
    .byte 0x10
    .byte 0x10
    .byte 0x10
    .byte 0x10
enddlabel __osIntOffTable

dlabel __osIntTable
    .word .L800CC828
    .word .L800CC7F0
    .word .L800CC7D0
    .word .L800CC634
    .word .L800CC5E0
    .word .L800CC774
    .word .L800CC5A8
    .word .L800CC5B4
    .word .L800CC5C0
    .word 0
    .word 0
    .word 0
enddlabel __osIntTable
