.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osGetCount
    /* CC7B0 800CBBB0 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* CC7B4 800CBBB4 03E00008 */  jr         $ra
    /* CC7B8 800CBBB8 00000000 */   nop
endlabel osGetCount
    /* CC7BC 800CBBBC 00000000 */  nop
