.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel __osDisableInt
    /* CC620 800CBA20 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* CC624 800CBA24 2401FFFE */  addiu      $at, $zero, -0x2
    /* CC628 800CBA28 01014824 */  and        $t1, $t0, $at
    /* CC62C 800CBA2C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* CC630 800CBA30 31020001 */  andi       $v0, $t0, 0x1
    /* CC634 800CBA34 00000000 */  nop
    /* CC638 800CBA38 03E00008 */  jr         $ra
    /* CC63C 800CBA3C 00000000 */   nop
endlabel __osDisableInt

/* Handwritten function */

glabel __osRestoreInt
    /* CC640 800CBA40 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* CC644 800CBA44 01044025 */  or         $t0, $t0, $a0
    /* CC648 800CBA48 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* CC64C 800CBA4C 00000000 */  nop
    /* CC650 800CBA50 00000000 */  nop
    /* CC654 800CBA54 03E00008 */  jr         $ra
    /* CC658 800CBA58 00000000 */   nop
endlabel __osRestoreInt
    /* CC65C 800CBA5C 00000000 */  nop
