.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osInvalICache
    /* D50F0 800D44F0 18A00011 */  blez       $a1, .L800D4538
    /* D50F4 800D44F4 00000000 */   nop
    /* D50F8 800D44F8 240B4000 */  addiu      $t3, $zero, 0x4000
    /* D50FC 800D44FC 00AB082B */  sltu       $at, $a1, $t3
    /* D5100 800D4500 1020000F */  beqz       $at, .L800D4540
    /* D5104 800D4504 00000000 */   nop
    /* D5108 800D4508 00804025 */  or         $t0, $a0, $zero
    /* D510C 800D450C 00854821 */  addu       $t1, $a0, $a1
    /* D5110 800D4510 0109082B */  sltu       $at, $t0, $t1
    /* D5114 800D4514 10200008 */  beqz       $at, .L800D4538
    /* D5118 800D4518 00000000 */   nop
    /* D511C 800D451C 310A001F */  andi       $t2, $t0, 0x1F
    /* D5120 800D4520 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* D5124 800D4524 010A4023 */  subu       $t0, $t0, $t2
  .L800D4528:
    /* D5128 800D4528 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* D512C 800D452C 0109082B */  sltu       $at, $t0, $t1
    /* D5130 800D4530 1420FFFD */  bnez       $at, .L800D4528
    /* D5134 800D4534 25080020 */   addiu     $t0, $t0, 0x20
  .L800D4538:
    /* D5138 800D4538 03E00008 */  jr         $ra
    /* D513C 800D453C 00000000 */   nop
  .L800D4540:
    /* D5140 800D4540 3C088000 */  lui        $t0, 0x8000
    /* D5144 800D4544 010B4821 */  addu       $t1, $t0, $t3
    /* D5148 800D4548 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L800D454C:
    /* D514C 800D454C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* D5150 800D4550 0109082B */  sltu       $at, $t0, $t1
    /* D5154 800D4554 1420FFFD */  bnez       $at, .L800D454C
    /* D5158 800D4558 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* D515C 800D455C 03E00008 */  jr         $ra
    /* D5160 800D4560 00000000 */   nop
endlabel osInvalICache
    /* D5164 800D4564 00000000 */  nop
    /* D5168 800D4568 00000000 */  nop
    /* D516C 800D456C 00000000 */  nop
