.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osInvalDCache
    /* CBBD0 800CAFD0 18A0001F */  blez       $a1, .L800CB050
    /* CBBD4 800CAFD4 00000000 */   nop
    /* CBBD8 800CAFD8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* CBBDC 800CAFDC 00AB082B */  sltu       $at, $a1, $t3
    /* CBBE0 800CAFE0 1020001D */  beqz       $at, .L800CB058
    /* CBBE4 800CAFE4 00000000 */   nop
    /* CBBE8 800CAFE8 00804025 */  or         $t0, $a0, $zero
    /* CBBEC 800CAFEC 00854821 */  addu       $t1, $a0, $a1
    /* CBBF0 800CAFF0 0109082B */  sltu       $at, $t0, $t1
    /* CBBF4 800CAFF4 10200016 */  beqz       $at, .L800CB050
    /* CBBF8 800CAFF8 00000000 */   nop
    /* CBBFC 800CAFFC 310A000F */  andi       $t2, $t0, 0xF
    /* CBC00 800CB000 11400007 */  beqz       $t2, .L800CB020
    /* CBC04 800CB004 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* CBC08 800CB008 010A4023 */  subu       $t0, $t0, $t2
    /* CBC0C 800CB00C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* CBC10 800CB010 0109082B */  sltu       $at, $t0, $t1
    /* CBC14 800CB014 1020000E */  beqz       $at, .L800CB050
    /* CBC18 800CB018 00000000 */   nop
    /* CBC1C 800CB01C 25080010 */  addiu      $t0, $t0, 0x10
  .L800CB020:
    /* CBC20 800CB020 312A000F */  andi       $t2, $t1, 0xF
    /* CBC24 800CB024 11400006 */  beqz       $t2, .L800CB040
    /* CBC28 800CB028 00000000 */   nop
    /* CBC2C 800CB02C 012A4823 */  subu       $t1, $t1, $t2
    /* CBC30 800CB030 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* CBC34 800CB034 0128082B */  sltu       $at, $t1, $t0
    /* CBC38 800CB038 14200005 */  bnez       $at, .L800CB050
    /* CBC3C 800CB03C 00000000 */   nop
  .L800CB040:
    /* CBC40 800CB040 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* CBC44 800CB044 0109082B */  sltu       $at, $t0, $t1
    /* CBC48 800CB048 1420FFFD */  bnez       $at, .L800CB040
    /* CBC4C 800CB04C 25080010 */   addiu     $t0, $t0, 0x10
  .L800CB050:
    /* CBC50 800CB050 03E00008 */  jr         $ra
    /* CBC54 800CB054 00000000 */   nop
  .L800CB058:
    /* CBC58 800CB058 3C088000 */  lui        $t0, 0x8000
    /* CBC5C 800CB05C 010B4821 */  addu       $t1, $t0, $t3
    /* CBC60 800CB060 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800CB064:
    /* CBC64 800CB064 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* CBC68 800CB068 0109082B */  sltu       $at, $t0, $t1
    /* CBC6C 800CB06C 1420FFFD */  bnez       $at, .L800CB064
    /* CBC70 800CB070 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* CBC74 800CB074 03E00008 */  jr         $ra
    /* CBC78 800CB078 00000000 */   nop
endlabel osInvalDCache
    /* CBC7C 800CB07C 00000000 */  nop
