.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osMapTLBRdb
    /* D5170 800D4570 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* D5174 800D4574 2409001F */  addiu      $t1, $zero, 0x1F
    /* D5178 800D4578 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* D517C 800D457C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* D5180 800D4580 240A0017 */  addiu      $t2, $zero, 0x17
    /* D5184 800D4584 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* D5188 800D4588 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* D518C 800D458C 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* D5190 800D4590 00095982 */  srl        $t3, $t1, 6
    /* D5194 800D4594 016A5825 */  or         $t3, $t3, $t2
    /* D5198 800D4598 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* D519C 800D459C 24090001 */  addiu      $t1, $zero, 0x1
    /* D51A0 800D45A0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* D51A4 800D45A4 00000000 */  nop
    /* D51A8 800D45A8 42000002 */  tlbwi /* handwritten instruction */
    /* D51AC 800D45AC 00000000 */  nop
    /* D51B0 800D45B0 00000000 */  nop
    /* D51B4 800D45B4 00000000 */  nop
    /* D51B8 800D45B8 00000000 */  nop
    /* D51BC 800D45BC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* D51C0 800D45C0 03E00008 */  jr         $ra
    /* D51C4 800D45C4 00000000 */   nop
endlabel osMapTLBRdb
    /* D51C8 800D45C8 00000000 */  nop
    /* D51CC 800D45CC 00000000 */  nop
