.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel __osProbeTLB
    /* D0350 800CF750 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* D0354 800CF754 310900FF */  andi       $t1, $t0, 0xFF
    /* D0358 800CF758 2401E000 */  addiu      $at, $zero, -0x2000
    /* D035C 800CF75C 00815024 */  and        $t2, $a0, $at
    /* D0360 800CF760 012A4825 */  or         $t1, $t1, $t2
    /* D0364 800CF764 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* D0368 800CF768 00000000 */  nop
    /* D036C 800CF76C 00000000 */  nop
    /* D0370 800CF770 00000000 */  nop
    /* D0374 800CF774 42000008 */  tlbp /* handwritten instruction */
    /* D0378 800CF778 00000000 */  nop
    /* D037C 800CF77C 00000000 */  nop
    /* D0380 800CF780 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* D0384 800CF784 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* D0388 800CF788 01615824 */  and        $t3, $t3, $at
    /* D038C 800CF78C 1560001A */  bnez       $t3, .L800CF7F8
    /* D0390 800CF790 00000000 */   nop
    /* D0394 800CF794 42000001 */  tlbr /* handwritten instruction */
    /* D0398 800CF798 00000000 */  nop
    /* D039C 800CF79C 00000000 */  nop
    /* D03A0 800CF7A0 00000000 */  nop
    /* D03A4 800CF7A4 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* D03A8 800CF7A8 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* D03AC 800CF7AC 000B5842 */  srl        $t3, $t3, 1
    /* D03B0 800CF7B0 01646024 */  and        $t4, $t3, $a0
    /* D03B4 800CF7B4 15800004 */  bnez       $t4, .L800CF7C8
    /* D03B8 800CF7B8 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* D03BC 800CF7BC 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* D03C0 800CF7C0 10000002 */  b          .L800CF7CC
    /* D03C4 800CF7C4 00000000 */   nop
  .L800CF7C8:
    /* D03C8 800CF7C8 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L800CF7CC:
    /* D03CC 800CF7CC 304D0002 */  andi       $t5, $v0, 0x2
    /* D03D0 800CF7D0 11A00009 */  beqz       $t5, .L800CF7F8
    /* D03D4 800CF7D4 00000000 */   nop
    /* D03D8 800CF7D8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* D03DC 800CF7DC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* D03E0 800CF7E0 00411024 */  and        $v0, $v0, $at
    /* D03E4 800CF7E4 00021180 */  sll        $v0, $v0, 6
    /* D03E8 800CF7E8 008B6824 */  and        $t5, $a0, $t3
    /* D03EC 800CF7EC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* D03F0 800CF7F0 10000002 */  b          .L800CF7FC
    /* D03F4 800CF7F4 00000000 */   nop
  .L800CF7F8:
    /* D03F8 800CF7F8 2402FFFF */  addiu      $v0, $zero, -0x1
  .L800CF7FC:
    /* D03FC 800CF7FC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* D0400 800CF800 03E00008 */  jr         $ra
    /* D0404 800CF804 00000000 */   nop
endlabel __osProbeTLB
    /* D0408 800CF808 00000000 */  nop
    /* D040C 800CF80C 00000000 */  nop
