.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel __osSetCompare
    /* D60F0 800D54F0 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* D60F4 800D54F4 03E00008 */  jr         $ra
    /* D60F8 800D54F8 00000000 */   nop
endlabel __osSetCompare
    /* D60FC 800D54FC 00000000 */  nop
