.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osSetIntMask
    /* C4DA0 800C41A0 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* C4DA4 800C41A4 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* C4DA8 800C41A8 3C08800F */  lui        $t0, %hi(__OSGlobalIntMask)
    /* C4DAC 800C41AC 2508CC4C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* C4DB0 800C41B0 8D0B0000 */  lw         $t3, 0x0($t0)
    /* C4DB4 800C41B4 2401FFFF */  addiu      $at, $zero, -0x1
    /* C4DB8 800C41B8 01614026 */  xor        $t0, $t3, $at
    /* C4DBC 800C41BC 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* C4DC0 800C41C0 00481025 */  or         $v0, $v0, $t0
    /* C4DC4 800C41C4 3C0AA430 */  lui        $t2, %hi(D_A430000C)
    /* C4DC8 800C41C8 8D4A000C */  lw         $t2, %lo(D_A430000C)($t2)
    /* C4DCC 800C41CC 11400005 */  beqz       $t2, .L800C41E4
    /* C4DD0 800C41D0 000B4C02 */   srl       $t1, $t3, 16
    /* C4DD4 800C41D4 2401FFFF */  addiu      $at, $zero, -0x1
    /* C4DD8 800C41D8 01214826 */  xor        $t1, $t1, $at
    /* C4DDC 800C41DC 3129003F */  andi       $t1, $t1, 0x3F
    /* C4DE0 800C41E0 01495025 */  or         $t2, $t2, $t1
  .L800C41E4:
    /* C4DE4 800C41E4 000A5400 */  sll        $t2, $t2, 16
    /* C4DE8 800C41E8 004A1025 */  or         $v0, $v0, $t2
    /* C4DEC 800C41EC 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* C4DF0 800C41F0 00814024 */  and        $t0, $a0, $at
    /* C4DF4 800C41F4 010B4024 */  and        $t0, $t0, $t3
    /* C4DF8 800C41F8 000843C2 */  srl        $t0, $t0, 15
    /* C4DFC 800C41FC 3C0A800F */  lui        $t2, %hi(__osRcpImTable)
    /* C4E00 800C4200 01485021 */  addu       $t2, $t2, $t0
    /* C4E04 800C4204 954AFEE0 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* C4E08 800C4208 3C01A430 */  lui        $at, %hi(D_A430000C)
    /* C4E0C 800C420C AC2A000C */  sw         $t2, %lo(D_A430000C)($at)
    /* C4E10 800C4210 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* C4E14 800C4214 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* C4E18 800C4218 01094024 */  and        $t0, $t0, $t1
    /* C4E1C 800C421C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* C4E20 800C4220 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* C4E24 800C4224 01816024 */  and        $t4, $t4, $at
    /* C4E28 800C4228 01886025 */  or         $t4, $t4, $t0
    /* C4E2C 800C422C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* C4E30 800C4230 00000000 */  nop
    /* C4E34 800C4234 00000000 */  nop
    /* C4E38 800C4238 03E00008 */  jr         $ra
    /* C4E3C 800C423C 00000000 */   nop
endlabel osSetIntMask
