.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osWritebackDCache
    /* CDB90 800CCF90 18A00011 */  blez       $a1, .L800CCFD8
    /* CDB94 800CCF94 00000000 */   nop
    /* CDB98 800CCF98 240B2000 */  addiu      $t3, $zero, 0x2000
    /* CDB9C 800CCF9C 00AB082B */  sltu       $at, $a1, $t3
    /* CDBA0 800CCFA0 1020000F */  beqz       $at, .L800CCFE0
    /* CDBA4 800CCFA4 00000000 */   nop
    /* CDBA8 800CCFA8 00804025 */  or         $t0, $a0, $zero
    /* CDBAC 800CCFAC 00854821 */  addu       $t1, $a0, $a1
    /* CDBB0 800CCFB0 0109082B */  sltu       $at, $t0, $t1
    /* CDBB4 800CCFB4 10200008 */  beqz       $at, .L800CCFD8
    /* CDBB8 800CCFB8 00000000 */   nop
    /* CDBBC 800CCFBC 310A000F */  andi       $t2, $t0, 0xF
    /* CDBC0 800CCFC0 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* CDBC4 800CCFC4 010A4023 */  subu       $t0, $t0, $t2
  .L800CCFC8:
    /* CDBC8 800CCFC8 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* CDBCC 800CCFCC 0109082B */  sltu       $at, $t0, $t1
    /* CDBD0 800CCFD0 1420FFFD */  bnez       $at, .L800CCFC8
    /* CDBD4 800CCFD4 25080010 */   addiu     $t0, $t0, 0x10
  .L800CCFD8:
    /* CDBD8 800CCFD8 03E00008 */  jr         $ra
    /* CDBDC 800CCFDC 00000000 */   nop
  .L800CCFE0:
    /* CDBE0 800CCFE0 3C088000 */  lui        $t0, 0x8000
    /* CDBE4 800CCFE4 010B4821 */  addu       $t1, $t0, $t3
    /* CDBE8 800CCFE8 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800CCFEC:
    /* CDBEC 800CCFEC BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* CDBF0 800CCFF0 0109082B */  sltu       $at, $t0, $t1
    /* CDBF4 800CCFF4 1420FFFD */  bnez       $at, .L800CCFEC
    /* CDBF8 800CCFF8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* CDBFC 800CCFFC 03E00008 */  jr         $ra
    /* CDC00 800CD000 00000000 */   nop
endlabel osWritebackDCache
    /* CDC04 800CD004 00000000 */  nop
    /* CDC08 800CD008 00000000 */  nop
    /* CDC0C 800CD00C 00000000 */  nop
