.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.2 */

/* Handwritten function */

glabel osWritebackDCacheAll
    /* C4E70 800C4270 3C088000 */  lui        $t0, 0x8000
    /* C4E74 800C4274 240A2000 */  addiu      $t2, $zero, 0x2000
    /* C4E78 800C4278 010A4821 */  addu       $t1, $t0, $t2
    /* C4E7C 800C427C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800C4280:
    /* C4E80 800C4280 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* C4E84 800C4284 0109082B */  sltu       $at, $t0, $t1
    /* C4E88 800C4288 1420FFFD */  bnez       $at, .L800C4280
    /* C4E8C 800C428C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* C4E90 800C4290 03E00008 */  jr         $ra
    /* C4E94 800C4294 00000000 */   nop
endlabel osWritebackDCacheAll
    /* C4E98 800C4298 00000000 */  nop
    /* C4E9C 800C429C 00000000 */  nop
